### ISSUE TITLE
Rename shard constant to `Shopify`?

### ISSUE THREAD

**Issue by grepsedawk** [the-business-factory/shopify.cr#5]
Ran into this with the fly.cr shard. I went with `Fly`

https://github.com/grepsedawk/fly.cr/blob/main/src/fly.cr#L6
https://github.com/grepsedawk/fly.cr/blob/main/shard.yml#L1

The constant giving away the service it's for, the repo name adding the .cr to let users know it's crystal.

**Comment by robcole** [comment]
Go for it! 👍
